"""Add is_deleted field to conversations

Revision ID: 002
Revises: 001
Create Date: 2025-06-20 15:17:35.401463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_conversations', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_conversations', 'is_deleted')
    # ### end Alembic commands ###