"""Remove is_archived column from conversations

Revision ID: 003
Revises: 002
Create Date: 2025-06-23 15:43:23.894831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_conversations', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_conversations', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###